# Let NetworkManager manage all devices on this system
network:
    ethernets:
      eth0:
        addresses:
          - 192.168.1.92/24
        nameservers:
          addresses:
            - 8.8.8.8
            - 8.8.4.4
        dhcp4: false
        routes:
          - to: default
            via: 192.168.1.1
    version: 2